// SafeTextBoxControl.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(SafeTextBoxControl.tlb)，该类型库将成为
// SafeTextBoxControl.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(B67B4780-D0E1-4017-9625-D8F1234092E9), version(1.0),
  control ]
library SafeTextBoxControlLib
{
	importlib(STDOLE_TLB);

	//  CSafeTextBoxControlCtrl 的主调度接口
	[ 
		uuid(DE709E5D-8662-4A83-9273-0AF359B91AB1)	
	]
	dispinterface _DSafeTextBoxControl
	{
		properties:
			[id(1)] BSTR SafeText;
			[id(2)] BSTR SafeKey;
	methods:
	};

	//  CSafeTextBoxControlCtrl 的事件调度接口

	[ 
		uuid(AD32A0DC-6667-45F0-9C64-F08C262C9372)	
	]
	dispinterface _DSafeTextBoxControlEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CSafeTextBoxControlCtrl 的类信息
	[
		uuid(0D40C51E-2774-4FF7-9462-57091653AA87)
	]
	coclass SafeTextBoxControl
	{
		[default] dispinterface _DSafeTextBoxControl;
		[default, source] dispinterface _DSafeTextBoxControlEvents;
	};

};
