// SafeTextBoxControl.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(SafeTextBoxControl.tlb)，该类型库将成为
// SafeTextBoxControl.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(B606A90E-BCA9-402E-8938-C58DB28AB81F), version(1.0),
  control ]
library SafeTextBoxControlLib
{
	importlib(STDOLE_TLB);

	//  CSafeTextBoxControlCtrl 的主调度接口
	[ 
		uuid(261FD803-3037-4D70-9C93-72B71965D100)	
	]
	dispinterface _DSafeTextBoxControl
	{
		properties:
		methods:
	};

	//  CSafeTextBoxControlCtrl 的事件调度接口

	[ 
		uuid(BB6E9CD7-4898-4140-A311-D6E9CAAA9555)	
	]
	dispinterface _DSafeTextBoxControlEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CSafeTextBoxControlCtrl 的类信息
	[
		uuid(98D55AFE-2E8B-4E93-9AD7-54EB5EAF31F5)
	]
	coclass SafeTextBoxControl
	{
		[default] dispinterface _DSafeTextBoxControl;
		[default, source] dispinterface _DSafeTextBoxControlEvents;
	};

};
